apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: quotes
  name: quotes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quotes
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: quotes
    spec:
      containers:
      - image: shahrilx/quotes:@BUILD_NUMBER
        name: quotes
        ports:
        - containerPort: 5000
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-svc
spec:
  type: NodePort
  selector:
    app: quotes  # Match the labels from your pod
  ports:
    - port: 5000  # Port exposed on the service
      targetPort: 5000  # Port on the container to forward traffic to
      nodePort: 30082  # NodePort value (between 30000-32767)

